# Generated by Django 6.0.7 on 2026-07-20 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiseAJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('github_url', models.URLField()),
                ('reference_branch', models.CharField(default='main', max_length=100)),
                ('criticality', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('critique', 'Critique')], default='moyen', max_length=10)),
                ('is_custom_fork', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('local_path', models.CharField(max_length=500)),
                ('reference_branch', models.CharField(default='main', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('notification_interne', 'Notification Interne'), ('teams_slack', 'Teams Slack')], default='notification_interne', max_length=25)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('mise_a_jour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.miseajour')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('non_integre', 'Non Integre'), ('up_to_date', 'Up To Date'), ('behind', 'Behind'), ('ahead', 'Ahead'), ('diverged', 'Diverged'), ('fork_personnalise', 'Fork Personnalise')], default='non_integre', max_length=20)),
                ('local_commit', models.CharField(blank=True, max_length=100, null=True)),
                ('github_commit', models.CharField(blank=True, max_length=100, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_modules', to='core.module')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_modules', to='core.project')),
            ],
            options={
                'unique_together': {('project', 'module')},
            },
        ),
        migrations.AddField(
            model_name='miseajour',
            name='project_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mises_a_jour', to='core.projectmodule'),
        ),
        migrations.AddField(
            model_name='project',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='projects', to='core.role'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.role')),
            ],
        ),
    ]
