# Generated by Django 6.0.7 on 2026-07-29 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_password_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_hash',
        ),
    ]
