# Generated by Django 6.0.7 on 2026-07-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='droits',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
