# Generated by Django 6.0.7 on 2026-07-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_role_droits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='droits',
        ),
        migrations.AddField(
            model_name='role',
            name='droit_alertes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='droit_consultation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='droit_consultation_projets_assignes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='droit_gestion_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='droit_vue_globale_statistiques',
            field=models.BooleanField(default=False),
        ),
    ]
